### ISSUE TITLE
Usuarios del proyecto

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#10]
- Usuario Administrador: podrá agregar nuevos Usuarios Aduaneros al sistema, además de revisar los datos desde el sitio de Administrador de Django.

- Usuario Aduanero: solamente tendrá acceso al sistema y sus funciones.

**Comment by ErickMartinez77** [comment]
Iniciando Usuarios del proyecto

**Comment by ghost** [comment]
Usuarios definidos

**Comment by ghost** [comment]
Usuarios descritos

**Comment by cricripaz** [comment]
Tarea Completada
