### ISSUE TITLE
Arquitectura frontend

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#12]
![arquifront](https://user-images.githubusercontent.com/49004994/99276627-37233800-2803-11eb-9a37-59dc058364d6.png)

Tecnologías:
- HTML5
- CSS3
- Bootstrap

**Comment by ErickMartinez77** [comment]
Iniciando Arquitectura frontend

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Tecnologías descritas

**Comment by cricripaz** [comment]
Tarea Completada
