### ISSUE TITLE
Arquitectura backend

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#13]
![arquiback](https://user-images.githubusercontent.com/49004994/99855764-eb9fbf80-2b5d-11eb-8672-a8db843c7a19.png)

Tecnologías:
- Django
- Python
- PostgreSQL

**Comment by ErickMartinez77** [comment]
Iniciando Arquitectura backend

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Tecnologías descritas

**Comment by cricripaz** [comment]
Tarea Completada
