### ISSUE TITLE
Use Case: Login Usuario Administrador DjandoAdmin

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#16]
Mockup
![loginAdmin](https://user-images.githubusercontent.com/49004994/99601970-ea905600-29d6-11eb-85a5-25930c27b3e0.png)

Diagrama
![useCase login admin](https://user-images.githubusercontent.com/49004994/99602066-288d7a00-29d7-11eb-9b35-74395f017181.png)

Story
Como Usuario Administrador, quiero ingresar al sitio de DjangoAdmin, para poder administrar los datos.

**Comment by ErickMartinez77** [comment]
Iniciando Use Case: Login Usuario Administrador DjandoAdmin

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
