### ISSUE TITLE
Use Case: Usuario Administrador añadir Usuario Aduanero

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#17]
Mockup
![menu](https://user-images.githubusercontent.com/49004994/99602921-b74ec680-29d8-11eb-85d6-cb1dfd689082.png)
![users](https://user-images.githubusercontent.com/49004994/99602944-c170c500-29d8-11eb-960d-e69baa350d2f.png)
![add](https://user-images.githubusercontent.com/49004994/99602954-c3d31f00-29d8-11eb-9a15-edb2e12f6ac2.png)

Diagrama
![useCase añadir usuario](https://user-images.githubusercontent.com/49004994/99603022-e49b7480-29d8-11eb-90dc-5597c603e996.png)

Story
Como Usuario Administrador, quiero añadir nuevos Usuarios Aduaneros, para que estos puedan monitorear las zonas francas.

**Comment by ErickMartinez77** [comment]
Iniciando Use Case: Usuario Administrador añadir Usuario Aduanero

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
