### ISSUE TITLE
Use Case: Usuario revisar las Zonas Francas

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#18]
Mockup
![zonas](https://user-images.githubusercontent.com/49004994/99691343-836ab400-2a5f-11eb-9701-c81264c8f960.png)

Diagrama
![useCase zonas](https://user-images.githubusercontent.com/49004994/99603651-1e20af80-29da-11eb-8b7c-b9cb987df399.png)

Story
Como Usuario Aduanero, quiero revisar las zonas francas, para poder ver sus inventarios.

**Comment by ErickMartinez77** [comment]
Iniciando Use Case: Usuario revisar las Zonas Francas

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
