### ISSUE TITLE
Use Case: Usuario revisa el Inventario de una Zona Franca específica

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#19]
Mockup
![inventario](https://user-images.githubusercontent.com/49004994/99691094-3ab2fb00-2a5f-11eb-9e11-f60d7fdb3739.png)

Diagrama
![useCase inventario](https://user-images.githubusercontent.com/49004994/99603815-7c4d9280-29da-11eb-9db1-ad9721ff628f.png)

Story
Como Usuario Aduanero, quiero ver el inventario de una zona franca en específico, para poder ver cuántos y cuáles objetos posee.

**Comment by ErickMartinez77** [comment]
Iniciando Use Case: Usuario revisa el Inventario de una Zona Franca específica

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
