### ISSUE TITLE
Introducción del proyecto

### ISSUE THREAD

**Issue by ErickMartinez77** [LosLillos/LosLillos#2]
El Gobierno boliviano ha establecido como una de sus prioridades fortalecer a la Aduana Nacional (AN) a través del Programa de Reforma y Modernización (PROMA), debido a los altos índices de corrupción, la ausencia de credibilidad y las bajas recaudaciones de esta institución. El objetivo principal de la reforma es facilitar el comercio, incrementar las recaudaciones y disminuir la corrupción. Uno de los resultados más importantes del programa de reforma fue la promulgación de la Ley General de Aduanas No.1990 el 28 de julio de 1999, la cual en su Artículo 254 determina que la AN implementará y mantendrá sistemas informáticos que permitan el cumplimiento de los regímenes aduaneros de manera adecuada.

**Comment by cricripaz** [comment]
Tarea Completada

**Comment by ErickMartinez77** [comment]
Iniciando Introducción del proyecto

**Comment by ghost** [comment]
Introducción definida

**Comment by ghost** [comment]
Introducción descrita

**Comment by cricripaz** [comment]
Tarea Completada
