### ISSUE TITLE
Use Case: añadir objeto inventario

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#20]
Mockup
![addObject](https://user-images.githubusercontent.com/49004994/99690939-0a6b5c80-2a5f-11eb-85e6-8f6c63010153.png)

Diagrama
![useCase añadir objeto inventario](https://user-images.githubusercontent.com/49004994/99690893-fb84aa00-2a5e-11eb-8f30-2cfbf2426561.png)

Story
Como Usuario Aduanero, quiero añadir un nuevo objeto al inventario de una zona franca, para mantener actualizada la base de datos.

**Comment by ErickMartinez77** [comment]
Iniciando Use Case: añadir objeto inventario

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
