### ISSUE TITLE
Use Case: ver un objeto del inventario a detalle

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#21]
Mockup
![objeto](https://user-images.githubusercontent.com/49004994/99691249-6635e580-2a5f-11eb-82ee-88b0b06e2c21.png)

Diagrama
![useCase objeto inventario](https://user-images.githubusercontent.com/49004994/99604318-8fad2d80-29db-11eb-80e3-d9cc67952200.png)

Story
Como Usuario Aduanero, quiero ver un objeto específico del inventario de una zona franca, para poder ver sus atributos con mayor detalle.

**Comment by ErickMartinez77** [comment]
Iniciando Use Case: ver un objeto del inventario a detalle

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
