### ISSUE TITLE
Use Case: filtrar inventario

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#23]
Mockup
![filtrar](https://user-images.githubusercontent.com/49004994/99690061-160a5380-2a5e-11eb-8e21-59a436a82651.png)

Diagrama
![useCase filtrar inventario](https://user-images.githubusercontent.com/49004994/99690158-3508e580-2a5e-11eb-96b2-db50a74a7bc1.png)

Story
Como Usuario Aduanero, quiero filtrar los objetos del inventario, para poder agruparlos según tenga la necesidad.

**Comment by ghost** [comment]
Iniciando Use Case: filtrar inventario

**Comment by ghost** [comment]
Mockup hecho

**Comment by ghost** [comment]
Diagrama hecho

**Comment by ghost** [comment]
Story hecho

**Comment by cricripaz** [comment]
Tarea Completada
