### ISSUE TITLE
Diagrama base de datos

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#25]
Entidades de la Base de Datos:
* Usuarios
* Zonas
* Objetos
![base_de_datos](https://user-images.githubusercontent.com/49013118/101114278-83b69380-35b7-11eb-82cf-c207c233b443.png)

**Comment by cricripaz** [comment]
iniciando diagrama

**Comment by cricripaz** [comment]
diagrama en progreso

**Comment by cricripaz** [comment]
diagrama terminado
