### ISSUE TITLE
Diagramas de secuencia

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#30]
Tareas:
- Diagrama de Secuencia de Eliminar Objeto
- Diagrama de Secuencia de Ver Inventario.
- Diagrama de Secuencia de Añadir Objeto.

**Comment by ErickMartinez77** [comment]
Iniciando diagrama de secuencia de Eliminar objeto

**Comment by ErickMartinez77** [comment]
Diagrama de secuencia de Eliminar objeto terminado.
![SecuenciaBorrarObjeto](https://user-images.githubusercontent.com/49004994/101294706-b0ed8680-37ef-11eb-92df-f74e2a96b925.png)

**Comment by ErickMartinez77** [comment]
Iniciando diagrama de secuencia de Ver Inventario.

**Comment by ErickMartinez77** [comment]
Diagrama de Secuencia de Ver Inventario terminado.
![SecuenciaVerInventario](https://user-images.githubusercontent.com/49004994/101294740-e8f4c980-37ef-11eb-88f8-fe39170d1ec2.png)

**Comment by ErickMartinez77** [comment]
Iniciando diagrama de Secuencia de Añadir Objeto.

**Comment by ErickMartinez77** [comment]
Diagrama de Secuencia de Añadir Objeto terminado.
![SecuenciaAñadirObjeto](https://user-images.githubusercontent.com/49004994/101294754-f9a53f80-37ef-11eb-847a-2c33364823fd.png)
