### ISSUE TITLE
Requerimientos del Proyecto

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#6]
- Autenticación de usuarios.
- Registro de nuevos usuarios aduaneros.
- Revisar la lista de las zonas francas registradas.
- Revisar el inventario de cualquier zona franca.
- Añadir nuevos objetos al inventario de una zona franca específica.
- Revisar en detalle un objeto del inventario de una zona franca.

**Comment by ErickMartinez77** [comment]
Iniciando Requerimientos del Proyecto

**Comment by ghost** [comment]
Requerimientos definidos

**Comment by ghost** [comment]
Requerimientos descritos

**Comment by cricripaz** [comment]
Tarea Completada
