### ISSUE TITLE
Objetivos del proyecto

### ISSUE THREAD

**Issue by ghost** [LosLillos/LosLillos#9]
El objetivo es el desarrollo e implementación de un sistema informático para la gestión de los procesos realizados en Zonas Francas, que involucran operaciones aduaneras y las relacionadas para un efectivo control de inventarios.

**Comment by ErickMartinez77** [comment]
Iniciando Objetivos del proyecto

**Comment by ghost** [comment]
Objetivos definidos

**Comment by ghost** [comment]
Objetivos descritos

**Comment by cricripaz** [comment]
Tarea Completada
